name: Run versionist
on:
  push:
    branches:
      - master

jobs:
  versionist:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - uses: tmigone/versionist-action@master
      with:
        github_email: 'Mustafamemon490@gmail.com'
        github_username: 'Mustafamemon'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        npm_token: ${{ secrets.NPM_TOKEN }}
